defmodule Brekitdown.AccountsTest do
  use Brekitdown.DataCase, async: true

  alias Brekitdown.Accounts

  import Brekitdown.AccountsFixtures
  alias Brekitdown.Accounts.{User, UserToken}

  describe "register_user/1" do
    test "requires email and password to be set" do
      {:error, changeset} = Accounts.register_user(%{})

      assert %{
               email: ["can't be blank"],
               password: ["can't be blank"]
             } = errors_on(changeset)
    end

    test "validates email format" do
      {:error, changeset} = Accounts.register_user(%{email: "not valid"})

      assert %{email: ["must have the @ sign and no spaces"]} = errors_on(changeset)
    end

    test "validates email length" do
      too_long = String.duplicate("db", 100)
      {:error, changeset} = Accounts.register_user(%{email: too_long})
      assert "should be at most 160 character(s)" in errors_on(changeset).email
    end

    test "validates email uniqueness (case-insensitively)" do
      %{email: email} = user_fixture()

      {:error, changeset} =
        Accounts.register_user(%{email: email, password: valid_user_password()})

      assert "has already been taken" in errors_on(changeset).email

      {:error, changeset} =
        Accounts.register_user(%{email: String.upcase(email), password: valid_user_password()})

      assert "has already been taken" in errors_on(changeset).email
    end

    test "validates password minimum length" do
      {:error, changeset} =
        Accounts.register_user(%{email: unique_user_email(), password: "too short"})

      assert "should be at least 12 character(s)" in errors_on(changeset).password
    end

    test "registers a user with a hashed password" do
      email = unique_user_email()
      {:ok, user} = Accounts.register_user(valid_user_attributes(email: email))

      assert user.email == email
      assert is_binary(user.hashed_password)
      # the plaintext password never survives the changeset
      assert is_nil(user.password)
      # email confirmation is a separate, not-yet-built workflow
      assert is_nil(user.confirmed_at)
      # the external id is generated by the database and loaded back
      assert user.reference_xid
    end
  end

  describe "get_user_by_email_and_password/2" do
    test "returns nil if the email does not exist" do
      refute Accounts.get_user_by_email_and_password("unknown@example.com", valid_user_password())
    end

    test "returns nil if the password is not valid" do
      user = user_fixture()
      refute Accounts.get_user_by_email_and_password(user.email, "invalid password")
    end

    test "returns the user if the email and password are valid" do
      %{id: id} = user = user_fixture()

      assert %User{id: ^id} =
               Accounts.get_user_by_email_and_password(user.email, valid_user_password())
    end
  end

  describe "generate_user_session_token/1" do
    setup do
      %{user: user_fixture()}
    end

    test "generates a unique token", %{user: user} do
      token = Accounts.generate_user_session_token(user)
      assert user_token = Repo.get_by(UserToken, token: token)
      assert user_token.context == "session"
      assert user_token.authenticated_at != nil

      # the same token cannot be reused for another user
      assert_raise Ecto.ConstraintError, fn ->
        Repo.insert!(%UserToken{
          token: user_token.token,
          user_id: user_fixture().id,
          context: "session"
        })
      end
    end

    test "carries the user's authenticated_at into the token", %{user: user} do
      user = %{user | authenticated_at: DateTime.add(DateTime.utc_now(:second), -3600)}
      token = Accounts.generate_user_session_token(user)
      assert user_token = Repo.get_by(UserToken, token: token)
      assert user_token.authenticated_at == user.authenticated_at
      assert DateTime.compare(user_token.inserted_at, user.authenticated_at) == :gt
    end
  end

  describe "get_user_by_session_token/1" do
    setup do
      user = user_fixture()
      token = Accounts.generate_user_session_token(user)
      %{user: user, token: token}
    end

    test "returns the user by token", %{user: user, token: token} do
      assert {session_user, token_inserted_at} = Accounts.get_user_by_session_token(token)
      assert session_user.id == user.id
      assert session_user.authenticated_at != nil
      assert token_inserted_at != nil
    end

    test "returns nil for an invalid token" do
      refute Accounts.get_user_by_session_token("oops")
    end

    test "returns nil for an expired token", %{token: token} do
      dt = ~N[2020-01-01 00:00:00]
      {1, nil} = Repo.update_all(UserToken, set: [inserted_at: dt, authenticated_at: dt])
      refute Accounts.get_user_by_session_token(token)
    end
  end

  describe "delete_user_session_token/1" do
    test "revokes the token" do
      user = user_fixture()
      token = Accounts.generate_user_session_token(user)
      assert Accounts.delete_user_session_token(token) == :ok
      refute Accounts.get_user_by_session_token(token)
    end
  end

  describe "inspect/2 for the User module" do
    test "does not include the password" do
      refute inspect(%User{password: "123456"}) =~ "password: \"123456\""
    end
  end
end
